language: python
python:
  - "2.7"
env:
  - TOX_ENV=py26zmq
  - TOX_ENV=py27zmq
  - TOX_ENV=py33zmq
  - TOX_ENV=py34zmq
  - TOX_ENV=py26nano
  - TOX_ENV=py27nano
  - TOX_ENV=py33nano
  - TOX_ENV=py34nano
  - TOX_ENV=py26fifo
  - TOX_ENV=py27fifo
  - TOX_ENV=py33fifo
  - TOX_ENV=py34fifo
install:
  - "pip install tox --download-cache $HOME/.pip-cache"
  - "pip install coveralls --download-cache $HOME/.pip-cache"
  - git clone --quiet --depth=100 "https://github.com/nanomsg/nanomsg.git" ~/builds/nanomsg
      && pushd ~/builds/nanomsg
      && ./autogen.sh
      && ./configure
      && make
      && sudo make install
      && popd;
script:
  - LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib tox -e $TOX_ENV
after_success:
  - coveralls
cache:
  directories:
    - .tox
    - $HOME/.pip-cache/
